# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 263ce4fe9ca099517b1fb31e01b9091ae5f2e909d7c971d3f564543656f9e697c1d16a8087bc086e551584c79dc654b127e667a7131e455b80cfa6686f898617

test:
  secret_key_base: 15c34cf2665af8037389518e45cbb1d090419ddb181065ac52c6ae45c759c107d1f4b23add24fd28f38d54b83ce48c439a649e16915721925c810b6daec7ad46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
